# Generated by Django 2.2.1 on 2019-07-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(default='Unknown Album', max_length=100)),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Release Date')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Artist', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(default='Unknown Song', max_length=100)),
                ('duration', models.IntegerField(default=0)),
                ('genre', models.IntegerField(choices=[(1, 'Unknown Genre'), (2, 'Rock'), (3, 'Pop'), (4, 'Ballad'), (5, 'EDM'), (6, 'Jazz'), (7, 'Hiphop')], default=1)),
                ('cover', models.ImageField(blank=True, default=None, null=True, upload_to='cover/')),
                ('album', models.ManyToManyField(blank=True, default=None, null=True, to='musics.Album')),
                ('artist', models.ManyToManyField(blank=True, default=None, null=True, to='musics.Artist')),
            ],
        ),
    ]
