# Generated by Django 2.2.1 on 2019-07-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(to='musics.Artist'),
        ),
    ]
