# Generated by Django 2.2.1 on 2019-07-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_auto_20190704_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='_music_album_+', to='musics.Album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(related_name='_music_artist_+', to='musics.Artist'),
        ),
    ]
