# Generated by Django 2.2.1 on 2019-07-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_auto_20190704_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='album', to='musics.Album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(related_name='artist', to='musics.Artist'),
        ),
    ]
