# Generated by Django 2.2.1 on 2019-07-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_auto_20190704_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='includes', to='musics.Album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(related_name='performs', to='musics.Artist'),
        ),
    ]
